netplan_configuration:
  network:
    version: 2
    bonds:
      bond0:
        addresses:
          - 10.48.10.152/24
        interfaces:
          - eno5
          - eno6
        parameters:
          mode: balance-alb
         
    ethernets:
      eno1:
        dhcp4: true
      eno5: {}
      eno6: {}
      ibs2f0:
        addresses:
          - 192.168.222.152/24
