---
- name: Add new user with admin rights
  hosts: '*'

  tasks:
  - name: Add admin user
    user:
      name: "{{ item.name }}" 
      password: "{{ item.pass }}" 
      shell: /bin/bash
      groups:
        - sudo
      append: yes 
      comment: Admin User
    loop: "{{ list_of_users }}"

  - name: Set authorized key
    authorized_key:
      user: "{{ item.name }}"
      state: present
      key: "{{ lookup('file', item.key) }}"
    loop: "{{ list_of_users }}"
